### ISSUE TITLE
Zipit Z2 Breakout v2.3 part issues

### ISSUE THREAD

**Issue by SHMAUS-Carter** [mozzwald/z2-breakout#1]
I was getting set to order a mini breakout board and I ran into a snag anyone know of a drop in replacement for.
- C1, C2: 4.7uF 6.3V 0603 (C1608X5R0J475K080AB) as that smd part is  Obsolete  and not availed at most suppliers.

**Comment by mozzwald** [comment]
Any 4.7uF 6.3V 0603 will work. Something like [CL10A475KQ8NNNC](https://www.digikey.com/en/products/detail/samsung-electro-mechanics/CL10A475KQ8NNNC/3886703) should work just fine
